name: Demo pass variables between jobs

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned, milestoned]
  issue_comment:
    types: [created, edited, deleted]
concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false    

jobs:
  prepareIterationPathJob:
    runs-on: ubuntu-latest
    outputs:
      ITERATION: ${{ steps.set-variable.outputs.MYVARIABLE }}
    steps:        
      - name: Set Iteration Path
        id: set-iteration
        run: |
          echo "MYVARIABLE=Hello World" >> $GITHUB_OUTPUT   

  Job2-ReadVariable:    
    needs: prepareIterationPathJob
    runs-on: ubuntu-latest    
    steps:
      - name: Read Job1 Variable
        id: read-variable
        run: echo "${{ needs.prepareIterationPathJob.outputs.MYVARIABLE }}"                          
